
//only for adviosy screen 
export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F4F7F2' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#346E3D', paddingHorizontal: 16, paddingVertical: 12, borderBottomLeftRadius: 16, borderBottomRightRadius: 16 },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold' },
  headerSub: { color: '#E1F0D7', fontSize: 13, marginTop: -2 },
  langBtn: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.15)', paddingVertical: 8, paddingHorizontal: 12, borderRadius: 20 },
  langBtnText: { color: '#fff', marginLeft: 6, fontSize: 14, fontWeight: '600' },
  messagesArea: { flex: 1 },
  messagesContent: { paddingHorizontal: 12, paddingVertical: 16 },
  messageRow: { flexDirection: 'row', marginBottom: 16, maxWidth: '85%' },
  messageRowBot: { alignSelf: 'flex-start' },
  messageRowUser: { alignSelf: 'flex-end' },
  avatar: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', backgroundColor: '#fff', marginRight: 8, borderWidth: 1, borderColor: '#E1F0D7' },
  bubble: { paddingHorizontal: 14, paddingVertical: 12, borderRadius: 18 },
  bubbleBot: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 5, elevation: 3 },
  bubbleUser: { backgroundColor: '#E1F0D7', borderTopRightRadius: 4,maxWidth:'100% ' },
  messageImage: { width: 250, height: 180, borderRadius: 12, marginBottom: 8, borderWidth: 1, borderColor: 'rgba(0,0,0,0.05)' },
  messageText: { fontSize: 16, lineHeight: 24 },
  messageTextUser: { color: '#25492b' },
  timestamp: { fontSize: 12, color: '#888', alignSelf: 'flex-end', marginTop: 4 },
  typingIndicator: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#fff', alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 10, borderRadius: 18, borderTopLeftRadius: 4, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2, elevation: 2 },
  typingText: { marginLeft: 8, color: '#555', fontSize: 15 },
  inputArea: { borderTopWidth: 1, borderColor: '#E0E5DA', backgroundColor: '#F4F7F2', paddingVertical: 8, paddingHorizontal: 12, paddingBottom: Platform.OS === 'ios' ? 16 : 8 },
  quickScroll: { paddingBottom: 10, paddingLeft: 2 },
  quickChip: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#E1F0D7', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 20, marginRight: 8, flexDirection: 'row', alignItems: 'center' },
  quickIcon: { fontSize: 16, marginRight: 6 },
  quickText: { fontSize: 14, color: '#346E3D', fontWeight: '500' },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  input: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 24, paddingHorizontal: 18, fontSize: 16, color: '#333', borderWidth: 1, borderColor: '#E0E5DA', paddingTop: Platform.OS === 'ios' ? 12 : 8, paddingBottom: Platform.OS === 'ios' ? 12 : 8, maxHeight: 120 },
  iconButton: { width: 48, height: 48, borderRadius: 24, justifyContent: 'center', alignItems: 'center' },
  micButton: { backgroundColor: '#346E3D' },
  micButtonActive: { backgroundColor: '#D32F2F' },
  sendButton: { backgroundColor: '#4CAF50' },
  sendButtonDisabled: { backgroundColor: '#B0C1B2' },
  listeningBox: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginTop: 8, padding: 8, backgroundColor: '#fff8e1', borderRadius: 12 },
  listeningText: { color: '#c66601', fontWeight: '600', marginLeft: 8 },
  modalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalImage: { width: '100%', height: '80%' },
  modalClose: { position: 'absolute', top: 50, right: 20, backgroundColor: 'rgba(0,0,0,0.5)', borderRadius: 20 },
  langModalBg: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  langModal: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 16, paddingBottom: 30, maxHeight: '70%' },
  langModalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 16, textAlign: 'center', color: '#333' },
  langItem: { paddingVertical: 14, paddingHorizontal: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderRadius: 10, marginBottom: 4 },
  langItemActive: { backgroundColor: '#F0F7EC' },
  langName: { fontSize: 16, color: '#444' },
  langNameActive: { fontWeight: '600', color: '#346E3D' },
  langClose: { marginTop: 20, alignItems: 'center', backgroundColor: '#F0F7EC', padding: 12, borderRadius: 12 },
  langCloseText: { color: '#346E3D', fontWeight: 'bold', fontSize: 16 },
});
